# Site settings
author: Sarah Jeanette
title: Cybernetic Chats
header-img: img/home-bg.png
email: sarahharrs@gmail.com
copyright_name: Sarah Jeanette
description: > # this means to ignore newlines until "baseurl:"
  Making technology do the work for you
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sarahharrs

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
